import test from 'node:test';
import assert from 'node:assert/strict';
import {newGame,act,playerView} from '../lib/games.ts';
const players=['a','b','c','d','e','f'];
function setup(n=4){return newGame('drawphone' as any,players.slice(0,n));}
function submit(g:any,id:string,text='猫在上班'){act(g,id,{type:'submit',taskKey:playerView(g,id).task.key,text});}
test('drawphone accepts 3–6 and starts a private text task for every player',()=>{for(let n=3;n<=6;n++){const g=setup(n);assert.equal(g.phase,'relay');for(const id of g.players){const v=playerView(g,id);assert.equal(v.task.kind,'text');assert.equal(v.previous,null);assert.equal(v.books,undefined);assert.equal(v.route,undefined);assert.equal(v.totalStages,n);}}assert.throws(()=>setup(2));});
test('every book visits each author exactly once; only preceding entry is visible',()=>{for(const n of [3,4,5,6]){const g=setup(n);for(let stage=0;stage<n;stage++){const tasks=g.players.map((id:string)=>({id,key:playerView(g,id).task.key}));for(const {id,key} of tasks){const v=playerView(g,id);assert.equal(v.stage,stage);assert.equal(v.task.kind,stage%2?'drawing':'text');assert.equal(v.revealedBooks,undefined);if(stage)assert.equal(v.previous.kind,stage%2?'text':'drawing');act(g,id,{type:'submit',taskKey:key,text:id+'的句子'});}}assert.equal(g.phase,'reveal');for(const book of g.books){assert.equal(book.entries.length,n);assert.equal(new Set(book.entries.map((e:any)=>e.author)).size,n);}assert.equal(playerView(g,'a').revealedBooks.length,1);assert.equal(playerView(g,'a').revealedBooks[0].entries.length,1);}});
test('submission locks task and rejects stale task or nonmember',()=>{const g=setup(3),key=playerView(g,'a').task.key;submit(g,'a');assert.equal(playerView(g,'a').task.submitted,true);assert.throws(()=>act(g,'a',{type:'draft',taskKey:key,text:'更改'}));assert.throws(()=>act(g,'a',{type:'submit',taskKey:key,text:'再提交'}));assert.throws(()=>act(g,'b',{type:'submit',taskKey:key,text:'冒充'}));assert.throws(()=>act(g,'x',{type:'submit',taskKey:key,text:'外人'}));submit(g,'b');submit(g,'c');assert.throws(()=>act(g,'a',{type:'submit',taskKey:key,text:'旧轮'}));});
import {drawphoneTick,drawphoneAct,phoneDrawingAccess} from '../lib/drawphone.ts';
test('timeout submits saved text and blank entries then advances exactly once',()=>{const g=setup(3);act(g,'a',{type:'draft',taskKey:playerView(g,'a').task.key,text:'企鹅吃火锅'});const deadline=g.deadline;assert.equal(drawphoneTick(g,deadline-1),false);assert.equal(drawphoneTick(g,deadline),true);assert.equal(g.stage,1);assert.equal(drawphoneTick(g,deadline),false);const textEntries=g.books.map((b:any)=>b.entries[0]);assert.equal(textEntries.find((e:any)=>e.author==='a').text,'企鹅吃火锅');assert.equal(textEntries.filter((e:any)=>e.missing).length,2);assert.ok(textEntries.every((e:any)=>e.timedOut));});
test('only assigned current drawing and immediate previous drawing are readable',()=>{const g=setup(4);for(const id of g.players)submit(g,id);const keys=g.players.map((id:string)=>playerView(g,id).task.key);for(let i=0;i<4;i++){const v=playerView(g,g.players[i]);assert.equal(phoneDrawingAccess(v,keys[i],true),true);assert.equal(phoneDrawingAccess(v,keys[(i+1)%4]),false);}for(const id of g.players)submit(g,id);for(const id of g.players){const v=playerView(g,id);assert.equal(phoneDrawingAccess(v,v.previous.key),true);assert.equal(phoneDrawingAccess(v,v.previous.key,true),false);assert.equal(keys.filter(k=>phoneDrawingAccess(v,k)).length,1);}});
test('reveal is host controlled, incremental and rejects duplicate advance; reactions rate limited',()=>{const g=setup(3);for(let s=0;s<3;s++)for(const id of g.players)submit(g,id);assert.throws(()=>act(g,'b',{type:'revealNext',cursor:0}));act(g,'a',{type:'revealNext',cursor:0});assert.throws(()=>act(g,'a',{type:'revealNext',cursor:0}));assert.equal(playerView(g,'b').revealedBooks[0].entries.length,2);drawphoneAct(g,'b',{type:'react',emoji:'😂'},1000);assert.throws(()=>drawphoneAct(g,'b',{type:'react',emoji:'😂'},1500));for(let cursor=1;cursor<9;cursor++)act(g,'a',{type:'revealNext',cursor});assert.equal(g.phase,'finished');assert.equal(playerView(g,'c').revealedBooks.length,3);assert.equal(g.winner,'draw');});
