import test from 'node:test';
import assert from 'node:assert/strict';
import { newGame, act, playerView } from '../lib/games.ts';
const ids=['a','b','c','d','e','f'];
function setup(n=6){return newGame('drawguess' as any,ids.slice(0,n));}
function choose(g:any){const secret=playerView(g,g.turn).choices[0];act(g,g.turn,{type:'choose',index:0,turnKey:g.turnKey});return secret;}
test('drawguess supports 2–6 people and isolates candidates and answers',()=>{for(const n of [2,3,4,5,6]){const g=setup(n);assert.equal(g.phase,'choose');assert.equal(playerView(g,'a').choices.length,3);assert.equal(playerView(g,'b').choices,undefined);const answer=choose(g);assert.equal(playerView(g,'a').answer,answer);assert.equal(playerView(g,'b').answer,undefined);assert.equal(playerView(g,'b').wordLength,Array.from(answer).length);}assert.throws(()=>setup(1));});
test('correct guesses receive rank scores once; drawer gains 20 per answer',()=>{const g=setup(),word=choose(g);for(let i=1;i<6;i++){act(g,ids[i],{type:'guess',text:word,turnKey:g.turnKey});assert.equal(g.scores[ids[i]],120-i*20);if(i<5){assert.equal(playerView(g,ids[i]).answer,undefined);assert.throws(()=>act(g,ids[i],{type:'guess',text:word,turnKey:g.turnKey}));}}assert.equal(g.scores.a,100);assert.equal(g.phase,'reveal');assert.equal(g.messages.filter((m:any)=>m.rank).length,5);});
test('reject drawer guessing, outsider, invalid choice, and stale turn',()=>{const g=setup();assert.throws(()=>act(g,'b',{type:'choose',index:0,turnKey:g.turnKey}));assert.throws(()=>act(g,'a',{type:'choose',index:99,turnKey:g.turnKey}));const word=choose(g);assert.throws(()=>act(g,'a',{type:'guess',text:word,turnKey:g.turnKey}));assert.throws(()=>act(g,'outsider',{type:'guess',text:word,turnKey:g.turnKey}));assert.throws(()=>act(g,'b',{type:'guess',text:word,turnKey:'old'}));});
test('wrong guesses are public but correct guesses never leak the word',()=>{const g=setup();const word=choose(g);act(g,'b',{type:'guess',text:'乱猜',turnKey:g.turnKey});assert.equal(playerView(g,'c').messages[0].text,'乱猜');act(g,'b',{type:'guess',text:' '+word+'！ ',turnKey:g.turnKey});assert.equal(g.scores.b,100);assert.equal(playerView(g,'c').messages[1].text,undefined);});
import { drawguessTick, drawguessAct, drawguessView } from '../lib/drawguess.ts';
test('server deadlines auto choose, reveal, rotate and finish ties',()=>{const g=setup(2);let time=g.deadline;assert.equal(drawguessTick(g,time-1),false);assert.equal(drawguessTick(g,time),true);assert.equal(g.phase,'drawing');assert.equal(drawguessTick(g,time),false);assert.throws(()=>drawguessAct(g,'b',{type:'guess',text:g.answer,turnKey:g.turnKey},g.deadline));time=g.deadline;drawguessTick(g,time);assert.equal(g.phase,'reveal');assert.equal(g.history.length,1);const old=g.turnKey;drawguessTick(g,g.deadline);assert.equal(g.turn,'b');assert.notEqual(g.turnKey,old);assert.equal(g.phase,'choose');for(let i=0;i<3;i++)drawguessTick(g,g.deadline);assert.equal(g.phase,'finished');assert.equal(g.winner,'draw');assert.equal(g.history.length,2);});
test('two rounds rotate every player twice; category appears only in last 30 seconds',()=>{const g=newGame('drawguess',ids.slice(0,2),{rounds:2});assert.equal(g.totalTurns,4);choose(g);assert.equal(drawguessView(g,'b',g.deadline-30001).category,undefined);assert.ok(drawguessView(g,'b',g.deadline-30000).category);for(let i=0;i<11;i++)drawguessTick(g,g.deadline);assert.equal(g.phase,'finished');assert.equal(g.history.length,4);});
