import test from 'node:test';
import assert from 'node:assert/strict';
import {xiangqiSetup,xiangqiAct,xiangqiView,xiangqiLegalMoves,xiangqiInCheck} from '../lib/xiangqi.ts';
import type {Game} from '../lib/games.ts';
const fresh=()=>{const g:Game={kind:'xiangqi',players:['red','black'],turn:'red',phase:'play',winner:null};xiangqiSetup(g);return g;};
test('initial position and turn privacy',()=>{const g=fresh();assert.equal(g.board.filter(Boolean).length,32);assert.equal(xiangqiLegalMoves(g.board,0).length,44);assert.equal(xiangqiView(g,'black').legalMoves.length,0);assert.throws(()=>xiangqiAct(g,'black',{type:'move',from:27,to:36}));});
test('horse legs, elephant river and pawn restrictions',()=>{const g=fresh();const legal=xiangqiLegalMoves(g.board,0);assert(!legal.some(m=>m.from===82&&m.to===75));assert(!legal.some(m=>m.from===54&&m.to===55));assert(legal.some(m=>m.from===54&&m.to===45));});
test('cannot expose facing generals',()=>{const b:any[]=Array(90).fill(null);b[4]={side:1,type:'k'};b[85]={side:0,type:'k'};b[49]={side:0,type:'r'};assert(!xiangqiLegalMoves(b,0).some(m=>m.from===49&&m.to===48));b[49]=null;assert(xiangqiInCheck(b,0));});
test('undo requires opponent agreement and restores two plies',()=>{const g=fresh(),start=JSON.stringify(g.board);xiangqiAct(g,'red',{type:'move',from:54,to:45});xiangqiAct(g,'black',{type:'move',from:27,to:36});xiangqiAct(g,'red',{type:'undo'});assert.throws(()=>xiangqiAct(g,'red',{type:'answerUndo',accept:true}));xiangqiAct(g,'black',{type:'answerUndo',accept:true});assert.equal(JSON.stringify(g.board),start);assert.equal(g.turn,'red');assert.equal(g.moves.length,0);assert.equal(g.positions.length,1);});
test('draw and resignation finish games',()=>{let g=fresh();xiangqiAct(g,'red',{type:'offerDraw'});xiangqiAct(g,'black',{type:'answerDraw',accept:true});assert.equal(g.winner,'draw');g=fresh();xiangqiAct(g,'red',{type:'resign'});assert.equal(g.winner,'black');assert.throws(()=>xiangqiAct(g,'black',{type:'undo'}));});
test('cannon needs exactly one screen to capture',()=>{const b:any[]=Array(90).fill(null);b[3]={side:1,type:'k'};b[85]={side:0,type:'k'};b[45]={side:0,type:'c'};b[9]={side:1,type:'r'};assert(!xiangqiLegalMoves(b,0).some(m=>m.from===45&&m.to===9));b[27]={side:0,type:'p'};assert(xiangqiLegalMoves(b,0).some(m=>m.from===45&&m.to===9));b[18]={side:1,type:'p'};assert(!xiangqiLegalMoves(b,0).some(m=>m.from===45&&m.to===9));});
test('checkmate and stalemate both lose',()=>{for(const mate of [true,false]){const g=fresh();g.board=Array(90).fill(null);g.board[4]={side:1,type:'k'};g.board[86]={side:0,type:'k'};g.board[21]={side:0,type:'r'};g.board[23]={side:0,type:'r'};g.board[36]={side:0,type:'r'};xiangqiAct(g,'red',{type:'move',from:36,to:mate?40:9});assert.equal(g.winner,'red');assert.equal(g.endReason,mate?'将死':'困毙');}});
test('pending decision belongs to opponent and histories stay private',()=>{const g=fresh();xiangqiAct(g,'red',{type:'offerDraw'});const v=xiangqiView(g,'black');assert.deepEqual(v.pendingPlayers,['black']);assert.equal((v as any).moves,undefined);xiangqiAct(g,'black',{type:'answerDraw',accept:false});assert.deepEqual(xiangqiView(g,'red').pendingPlayers,['red']);});


test('three repeated full positions finish as draw and reject later moves',()=>{const g=fresh();for(let cycle=0;cycle<2;cycle++){xiangqiAct(g,'red',{type:'move',from:82,to:63});xiangqiAct(g,'black',{type:'move',from:1,to:18});xiangqiAct(g,'red',{type:'move',from:63,to:82});xiangqiAct(g,'black',{type:'move',from:18,to:1});}assert.equal(g.winner,'draw');assert.equal(g.endReason,'三次重复和棋');assert.throws(()=>xiangqiAct(g,'red',{type:'move',from:54,to:45}));});
test('undo rejects self approval and pauses moves until answered',()=>{const g=fresh();xiangqiAct(g,'red',{type:'move',from:54,to:45});xiangqiAct(g,'red',{type:'undo'});assert.throws(()=>xiangqiAct(g,'black',{type:'move',from:27,to:36}));xiangqiAct(g,'black',{type:'answerUndo',accept:false});assert.equal(g.turn,'black');assert.equal(g.moves.length,1);});
