'use client';
import {PointerEvent as ReactPointerEvent,useCallback,useEffect,useMemo,useRef,useState} from 'react';
import './drawguess-game.css';
export type DrawguessStroke={id:string;color:string;width:number;points:[number,number][]};
type DrawOp={code:string;turnKey:string;opId:string;type:'stroke'|'undo'|'clear';stroke?:DrawguessStroke};
const colors=['#263238','#ef5350','#ff9800','#fdd835','#66bb6a','#42a5f5','#ab47bc','#795548'];
const widths=[3,8,16];
const MAX_LOCAL_STROKES=2500;
const id=()=>globalThis.crypto?.randomUUID?.()||`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
const storageKey=(code:string,turnKey:string)=>`drawguess-queue:${code}:${turnKey}`;
function readQueue(code:string,turnKey:string):DrawOp[]{try{const value=JSON.parse(localStorage.getItem(storageKey(code,turnKey))||'[]');return Array.isArray(value)?value.filter(v=>v?.turnKey===turnKey&&v?.code===code).slice(-2500):[];}catch{return [];}}
function saveQueue(code:string,turnKey:string,value:DrawOp[]){try{value.length?localStorage.setItem(storageKey(code,turnKey),JSON.stringify(value)):localStorage.removeItem(storageKey(code,turnKey));}catch{/* Private mode or a full quota must not stop drawing. */}}
function applyOps(base:DrawguessStroke[],ops:DrawOp[]){let out=base;for(const op of ops){if(op.type==='stroke'&&op.stroke){if(!out.some(v=>v.id===op.stroke!.id))out=[...out,op.stroke];}else if(op.type==='undo')out=out.slice(0,-1);else out=[];}return out.slice(-MAX_LOCAL_STROKES);}

export function DrawingCanvas({code,turnKey,editable,active,onPendingChange,emptyLabel}:{code:string;turnKey:string;editable:boolean;active:boolean;onPendingChange?:(pending:boolean)=>void;emptyLabel?:string}){
 const [loaded,setLoaded]=useState(false);
 const [serverStrokes,setServerStrokes]=useState<DrawguessStroke[]>([]),[queue,setQueue]=useState<DrawOp[]>([]),[draft,setDraftState]=useState<DrawguessStroke|null>(null);
 const [color,setColor]=useState(colors[0]),[width,setWidth]=useState(8),[eraser,setEraser]=useState(false),[sync,setSync]=useState<'ok'|'saving'|'retry'|'rejected'>('ok');
 const queueRef=useRef<DrawOp[]>([]),draftRef=useRef<DrawguessStroke|null>(null),pointerId=useRef<number|null>(null),acked=useRef(new Set<string>()),terminal=useRef(false),generation=useRef(0),activeTurn=useRef(turnKey),activeRef=useRef(active),fetchSequence=useRef(0),appliedSequence=useRef(0),fetchState=useRef({revision:0,total:0}),busy=useRef(false),svgRef=useRef<SVGSVGElement>(null),lastPoint=useRef<[number,number]|null>(null),lastAt=useRef(0),segmentStarted=useRef(0);
 useEffect(()=>{activeRef.current=active;},[active]);
 const setDraft=(value:DrawguessStroke|null)=>{draftRef.current=value;setDraftState(value);};
 const updateQueue=useCallback((next:DrawOp[])=>{queueRef.current=next;setQueue(next);saveQueue(code,turnKey,next);},[code,turnKey]);
 const fetchDrawing=useCallback(async(full=false)=>{const gen=generation.current,requestTurn=turnKey,sequence=++fetchSequence.current;const s={...fetchState.current};const q=new URLSearchParams({code,turnKey});if(!full){q.set('revision',String(s.revision));q.set('after',String(s.total));}const res=await fetch(`/api/drawing?${q}`,{cache:'no-store'});if(!res.ok)throw new Error('fetch');const data:any=await res.json();if(gen!==generation.current||requestTurn!==activeTurn.current||sequence<appliedSequence.current)return;const revision=Number(data.revision)||0,total=Number(data.total)||0,current=fetchState.current;if(revision<current.revision||(revision===current.revision&&total<current.total))return;appliedSequence.current=sequence;const incoming=(data.strokes||[]) as DrawguessStroke[];setServerStrokes(old=>{const replace=data.reset||full||revision!==current.revision;if(replace)return incoming.slice(-MAX_LOCAL_STROKES);const known=new Set(old.map(v=>v.id));return [...old,...incoming.filter(v=>!known.has(v.id))].slice(-MAX_LOCAL_STROKES);});fetchState.current={revision,total};setLoaded(true);if(incoming.length){const ids=new Set(incoming.map(v=>v.id));const next=queueRef.current.filter(op=>op.type!=='stroke'||!op.stroke||!ids.has(op.stroke.id));if(next.length!==queueRef.current.length)updateQueue(next);}},[code,turnKey,updateQueue]);
 const pump=useCallback(async()=>{if(!activeRef.current||busy.current||terminal.current||!queueRef.current.length)return;busy.current=true;setSync('saving');const gen=generation.current;try{while(activeRef.current&&queueRef.current.length&&gen===generation.current){const op=queueRef.current[0];if(!acked.current.has(op.opId)){const res=await fetch('/api/drawing',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(op)});if(res.status>=400&&res.status<500){terminal.current=true;setSync('rejected');throw new Error('rejected');}if(!res.ok)throw new Error('post');acked.current.add(op.opId);}if(op.type==='stroke'){
     await fetchDrawing(false);
     if(queueRef.current[0]?.opId===op.opId)break;
    }else{await fetchDrawing(true);if(queueRef.current[0]?.opId===op.opId)updateQueue(queueRef.current.slice(1));acked.current.delete(op.opId);}
   }if(gen===generation.current&&queueRef.current.length===0)setSync('ok');
  }catch{if(gen===generation.current&&!terminal.current)setSync('retry');}finally{busy.current=false;}},[fetchDrawing,updateQueue]);
 useEffect(()=>{generation.current++;busy.current=false;terminal.current=false;acked.current.clear();fetchSequence.current=0;appliedSequence.current=0;fetchState.current={revision:0,total:0};setServerStrokes([]);setDraft(null);const restored=readQueue(code,turnKey);queueRef.current=restored;setQueue(restored);setSync(restored.length?'saving':'ok');fetchDrawing(true).catch(()=>setSync('retry'));return()=>{generation.current++;busy.current=false;};},[code,turnKey,fetchDrawing]);
 useEffect(()=>{const timer=setInterval(()=>{fetchDrawing(false).then(()=>{if(active)pump();}).catch(()=>setSync(queueRef.current.length?'retry':'ok'));},1200);if(active)pump();return()=>clearInterval(timer);},[active,fetchDrawing,pump,queue.length]);
 const enqueue=useCallback((type:DrawOp['type'],stroke?:DrawguessStroke)=>{const op:DrawOp={code,turnKey,opId:id(),type,...(stroke?{stroke}:{})};updateQueue([...queueRef.current,op]);setSync('saving');setTimeout(()=>pump(),0);},[code,turnKey,pump,updateQueue]);
 const point=(e:ReactPointerEvent<SVGSVGElement>):[number,number]=>{const box=svgRef.current!.getBoundingClientRect();return [Math.max(0,Math.min(800,(e.clientX-box.left)*800/box.width)),Math.max(0,Math.min(500,(e.clientY-box.top)*500/box.height))];};
 const start=(e:ReactPointerEvent<SVGSVGElement>)=>{if(!e.isPrimary||pointerId.current!==null||!editable||queue.some(v=>v.type!=='stroke'))return;pointerId.current=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);const p=point(e),s={id:id(),color:eraser?'#ffffff':color,width:eraser?16:width,points:[p] as [number,number][]};lastPoint.current=p;lastAt.current=performance.now();segmentStarted.current=lastAt.current;setDraft(s);};
 const movePointer=(e:ReactPointerEvent<SVGSVGElement>)=>{const current=draftRef.current;if(e.pointerId!==pointerId.current||!current||!editable)return;const p=point(e),last=lastPoint.current,now=performance.now();if(last&&now-lastAt.current<12&&Math.hypot(p[0]-last[0],p[1]-last[1])<2)return;lastPoint.current=p;lastAt.current=now;const points=[...current.points,p] as [number,number][];if(points.length>=200||(points.length>1&&now-segmentStarted.current>=400)){enqueue('stroke',{...current,points});segmentStarted.current=now;setDraft({...current,id:id(),points:[points[points.length-1]]});}else setDraft({...current,points});};
 const finish=(e?:ReactPointerEvent<SVGSVGElement>)=>{if(e&&e.pointerId!==pointerId.current)return;const current=draftRef.current;pointerId.current=null;if(!current)return;if(current.points.length===1){const [x,y]=current.points[0];current.points.push([Math.min(800,x+.01),Math.min(500,y+.01)]);}enqueue('stroke',current);setDraft(null);lastPoint.current=null;};
 useEffect(()=>{if(!editable&&draft)finish();},[editable]);
 const hasDraft=!!draft;
 useEffect(()=>{onPendingChange?.(!loaded||queue.length>0||hasDraft);},[onPendingChange,loaded,queue.length,hasDraft]);
 const visible=useMemo(()=>active?applyOps(serverStrokes,queue).concat(draft?[draft]:[]):serverStrokes,[active,serverStrokes,queue,draft]);const controlsPending=queue.some(v=>v.type!=='stroke');
 return <div className="dg-canvas-shell">
  <svg ref={svgRef} className={`dg-canvas ${editable?'can-draw':''}`} viewBox="0 0 800 500" role="img" aria-label={editable?'绘画区域':'玩家画作'} onPointerDown={start} onPointerMove={movePointer} onPointerUp={finish} onPointerCancel={finish} onContextMenu={e=>e.preventDefault()}>
   <rect width="800" height="500" fill="#fff"/>{visible.map(s=><polyline key={s.id} points={s.points.map(p=>p.join(',')).join(' ')} fill="none" stroke={s.color} strokeWidth={s.width} strokeLinecap="round" strokeLinejoin="round"/>)}
  </svg>
  {editable&&<div className="dg-tools" aria-label="画笔工具"><div className="dg-palette">{colors.map(c=><button key={c} style={{background:c}} className={!eraser&&color===c?'active':''} aria-label={`选择颜色 ${c}`} onClick={()=>{setColor(c);setEraser(false);}}/>)}</div><div className="dg-widths">{widths.map(w=><button key={w} className={!eraser&&width===w?'active':''} onClick={()=>{setWidth(w);setEraser(false);}}><i style={{width:w,height:w}}/> </button>)}</div><button className={eraser?'active':''} onClick={()=>setEraser(!eraser)}>橡皮</button><button disabled={controlsPending||!visible.length} onClick={()=>enqueue('undo')}>撤销上一段</button><button disabled={controlsPending||!visible.length} onClick={()=>{if(window.confirm('确定清空整幅画吗？'))enqueue('clear');}}>清空</button><span className={`dg-sync ${sync}`}>{sync==='ok'?'已保存':sync==='saving'?'保存中…':sync==='rejected'?'未能保存，画作已保留':'网络不稳，正在重试'}</span></div>}
  {!active&&loaded&&serverStrokes.length===0&&emptyLabel&&<p className="dg-sync-note">{emptyLabel}</p>}
  {!active&&queue.length>0&&<p className="dg-sync-note">本机仍保留未保存的画笔操作；这里展示的是大家都能看到的已保存画作。</p>}
 </div>;
}

export function DrawingCountdown({deadline,serverNow}:{deadline:number;serverNow:number}){const [left,setLeft]=useState(()=>Math.max(0,deadline-serverNow));useEffect(()=>{const started=Date.now(),base=Math.max(0,deadline-serverNow);const tick=()=>setLeft(Math.max(0,base-(Date.now()-started)));tick();const timer=setInterval(tick,250);return()=>clearInterval(timer);},[deadline,serverNow]);return <span className={left<10000?'urgent':''}>{Math.ceil(left/1000)} 秒</span>}
