'use client';
import {useEffect,useState,CSSProperties} from 'react';
import {avatarColors} from '../lib/presentation';
import {SG_EFFECTS,SGCard} from '../lib/sanguosha';
import './sanguosha-game.css';
type Props={g:any;me:string;disabled:boolean;move:(a:any)=>void;playerName:(id:string)=>string;roomPlayers?:any[]};
const roles:Record<string,string>={lord:'主公',loyal:'忠臣',rebel:'反贼',renegade:'内奸'};
const slots:Record<string,string>={weapon:'武器',armor:'防具',offHorse:'进攻马',defHorse:'防御马'};
const positions:Record<number,number[][]>={2:[[50,18]],3:[[24,25],[76,25]],4:[[17,38],[50,16],[83,38]],5:[[16,43],[30,16],[70,16],[84,43]],6:[[15,46],[19,18],[50,14],[81,18],[85,46]]};
const active=['仁德','制衡','青囊','结姻','苦肉','反间','离间','激将'];
const convert=['武圣','倾国','龙胆','奇袭','国色','急救'];
function Card({c,chosen,click,disabled=false}:{c:SGCard;chosen?:boolean;click?:()=>void;disabled?:boolean}){return <button type="button" className={`sg-card ${chosen?'selected':''} ${['♥','♦'].includes(c.suit)?'red':''}`} onClick={click} disabled={disabled} title={`${c.name} · ${c.type}：${SG_EFFECTS[c.name]||''}`}><small>{c.suit} {({1:'A',11:'J',12:'Q',13:'K'} as Record<number,string>)[c.rank]||c.rank}</small><b>{c.name}</b><span>{c.type}</span></button>}
export function SanguoshaGame({g,me,disabled,move,playerName,roomPlayers=[]}:Props){
 const [cards,setCards]=useState<string[]>([]),[targets,setTargets]=useState<string[]>([]),[skill,setSkill]=useState(''),[info,setInfo]=useState(''),[top,setTop]=useState<string[]>([]),[bottom,setBottom]=useState<string[]>([]);
 const mine=g.seats.find((s:any)=>s.id===me),r=g.pending,responding=r?.player===me,playing=!r&&g.turn===me&&g.phase==='play',can=!disabled&&!g.winner&&mine?.alive&&(playing||responding);
 const [turnTip,setTurnTip]=useState(false);const acting=(g.pendingPlayers||[]).includes(me)&&!g.winner;
 useEffect(()=>{if(!acting){setTurnTip(false);return}setTurnTip(true);const timer=setTimeout(()=>setTurnTip(false),3000);return()=>clearTimeout(timer)},[acting]);
 const key=JSON.stringify([g.turn,g.phase,r,g.hand?.map((c:SGCard)=>c.id)]);
 useEffect(()=>{setCards([]);setTargets([]);setSkill('');setTop(r?.kind==='guanxing'&&r.player===me?r.cards.map((c:SGCard)=>c.id):[]);setBottom([])},[key]);
 const send=(a:any)=>{move(a);};
 const toggleCard=(c:SGCard)=>{setInfo(`${c.name} · ${c.type}：${SG_EFFECTS[c.name]||''}`);setCards(v=>v.includes(c.id)?v.filter(x=>x!==c.id):[...v,c.id]);};
 const payload={cards,card:cards[0],target:targets[0],targets,secondaryTarget:targets[1],...(skill?{skill}:{})};
 const others=g.players.filter((p:string)=>p!==me);const myIndex=g.players.indexOf(me);if(myIndex>=0)others.sort((a:string,b:string)=>(g.players.indexOf(a)-myIndex+g.players.length)%g.players.length-(g.players.indexOf(b)-myIndex+g.players.length)%g.players.length);
 const names=(ids:string[])=>ids.map(playerName).join('、');
 const hints:Record<string,string>={respond:`请打出${r?.need||'闪'}${r?.remaining>1?`，还需 ${r.remaining} 张`:''}`,nullify:`是否用无懈可击${r?.chain?.negated?'恢复':'抵消'}当前锦囊？`,dying:`${r?.job?.target?playerName(r.job.target):'角色'}濒死，请出桃救助`,assist:`${r?.requester?playerName(r.requester):'主公'}请求代出${r?.need||'杀'}`,collateral:'借刀杀人：打出杀攻击指定角色，或交出武器',discard:`请选择 ${r?.count} 张手牌弃置`,drawSkill:`是否发动${r?.skill}？${r?.skill==='突袭'?'选择一至两名有手牌的其他角色。':''}`,guanxing:'观星：按显示顺序安排牌堆顶与牌堆底，左侧先摸',luoshen:'洛神：继续判定，黑色获得，红色停止',guicai:'鬼才：选择一张手牌替换判定牌，或保留原判定',ganglie:'刚烈：弃两张手牌，或受到一点伤害',trigger:`是否发动${r?.skill}？`,yiji:'遗计：选择刚摸到的牌和一名其他角色赠送，可分次分配',zone:'选择目标的一张手牌、装备或判定牌',harvest:'五谷丰登：选择一张牌收入手牌',fanjian:'反间：猜一种花色',liuli:'流离：选择一张牌弃置，再选择另一名攻击范围内角色',cixiong:'雌雄双股剑：弃一张手牌，或让对方摸一张',weaponFollow:r?.weapon==='贯石斧'?'贯石斧：弃两张其他牌强制命中':'青龙偃月刀：打出杀继续追击',horse:'麒麟弓：选择弃置目标的一匹马'};
 const seat=(s:any,i:number,self=false)=>{const pos=self?[50,70]:(positions[g.players.length]||positions[6])[i];return <article key={s.id} className={`sg-seat ${self?'self':''} ${targets.includes(s.id)?'targeted':''} ${!s.alive?'dead':''} ${(g.pendingPlayers||[]).includes(s.id)?'turn':''}`} style={{'--sg-color':roomPlayers.find((p:any)=>p.id===s.id)?.color||avatarColors[g.players.indexOf(s.id)%6],left:`${pos[0]}%`,top:`${pos[1]}%`} as CSSProperties}><button className="sg-person" disabled={!can||!s.alive} onClick={()=>setTargets(v=>v.includes(s.id)?v.filter(x=>x!==s.id):[...v,s.id])}><span className="sg-avatar">{Array.from(playerName(s.id))[0]}{self&&turnTip&&<small className="sg-turn-tip">轮到你了</small>}</span><span><strong>{playerName(s.id)}{self?' · 你':''}</strong><small>{roomPlayers.find((p:any)=>p.id===s.id)?.away?'已返回大厅 · ':''}{roles[s.role]||'身份未知'} · 手牌 {s.handCount}{!s.alive?' · 阵亡':''}{targets.includes(s.id)?` · 目标${targets.indexOf(s.id)+1}`:''}</small></span></button><div className="sg-hero"><b>{s.hero?.name||'选择武将中'}</b><span>{s.hero?.faction} · {s.hp}/{s.maxHp} ♥</span></div><div className="sg-skills">{s.hero?.skills.map((n:string)=><button key={n} onClick={()=>setInfo(`${s.hero.name} · ${s.hero.text}`)}>{n} ⓘ</button>)}</div><div className="sg-equipment">{Object.entries(slots).map(([k,n])=>{const c=s.equipment[k];return <button key={k} className={`${c?'filled':''} ${c&&cards.includes(c.id)?'selected':''}`} onClick={()=>{if(c){setInfo(`${c.name}：${SG_EFFECTS[c.name]||''}`);if(self&&can)toggleCard(c)}}}>{n}<br/>{c?.name||'—'}</button>})}</div>{s.delayed?.length>0&&<div className="sg-delayed">判定：{s.delayed.map((c:SGCard)=>c.name).join('、')}</div>}</article>};
 const zoneTarget=g.seats.find((s:any)=>s.id===(r?.job?.target||r?.target));
 const required=['discard','guanxing','zone','harvest','fanjian'].includes(r?.kind);
 return <section className="sg-game"><header><div><h2>三国杀 · 身份局</h2><p>2–6 人 · 五张起手牌 · 武将与技能公开，身份暗藏</p></div><span>第 {g.round||0} 回合 · 牌堆 {g.deckCount}</span></header><div className="sg-table">{others.map((p:string,i:number)=>seat(g.seats.find((s:any)=>s.id===p),i))}{mine&&seat(mine,0,true)}<div className="sg-center"><b>{g.winner?`${g.winner==='lord'?'主公与忠臣':g.winner==='rebels'?'反贼':'内奸'}获胜`:g.phase==='selectHero'?'群雄待命':`${playerName(r?.player||g.turn)}${r?'响应中':'的回合'}`}</b><p>{g.lastCard?`最近弃牌：${g.lastCard.suit}${g.lastCard.rank} ${g.lastCard.name}`:'身份已分配，准备开局'}</p><div className="sg-latest">{g.log?.slice(-2).map((s:string,i:number)=><div key={i}>{s}</div>)}</div></div></div>
 <div className="sg-control"><p className="sg-prompt" role="status">{g.winner?'本局结束':responding?hints[r.kind]||'请选择响应':playing?'选择手牌和目标，然后出牌；技能也可使用已选牌与目标。':g.phase==='selectHero'?'等待所有玩家选定武将':'等待其他玩家操作'}</p>{responding&&r.kind==='guicai'&&r.judgment?.card&&<p>当前判定：{r.judgment.card.suit}{r.judgment.card.rank} {r.judgment.card.name}</p>}
 {responding&&r.kind==='guanxing'&&<div className="sg-guanxing">{[['牌堆顶',top],['牌堆底',bottom]].map(([title,ids])=><div key={title as string}><strong>{title as string}（从左到右）</strong><div className="sg-hand">{(ids as string[]).map((id,i)=>{const c=r.cards.find((x:SGCard)=>x.id===id);return <div key={id}><Card c={c}/><div><button disabled={disabled||i===0} onClick={()=>{const a=[...(ids as string[])];[a[i-1],a[i]]=[a[i],a[i-1]];title==='牌堆顶'?setTop(a):setBottom(a)}}>←</button><button disabled={disabled} onClick={()=>{if(title==='牌堆顶'){setTop(top.filter(x=>x!==id));setBottom([...bottom,id])}else{setBottom(bottom.filter(x=>x!==id));setTop([...top,id])}}}>移至{title==='牌堆顶'?'底':'顶'}</button></div></div>})}</div></div>)}<button disabled={disabled} onClick={()=>send({type:'respond',top,bottom})}>确认顺序</button></div>}
 {responding&&r.kind==='harvest'&&<div className="sg-hand">{r.cards.map((c:SGCard)=><Card key={c.id} c={c} disabled={disabled} click={()=>send({type:'respond',card:c.id})}/>)}</div>}
 {responding&&['zone','horse'].includes(r.kind)&&zoneTarget&&<div className="sg-actions">{r.kind==='zone'&&zoneTarget.handCount>0&&<button disabled={disabled} onClick={()=>send({type:'respond',zone:'hand'})}>随机手牌（{zoneTarget.handCount}）</button>}{Object.entries(slots).filter(([k])=>r.kind!=='horse'||k.includes('Horse')).map(([k,n])=>zoneTarget.equipment[k]&&<button key={k} disabled={disabled} onClick={()=>send({type:'respond',zone:k})}>{n}：{zoneTarget.equipment[k].name}</button>)}{r.kind==='zone'&&!r.job.noDelayed&&zoneTarget.delayed.map((c:SGCard)=><button key={c.id} disabled={disabled} onClick={()=>send({type:'respond',zone:'delayed',card:c.id})}>判定：{c.name}</button>)}</div>}
 {responding&&r.kind==='fanjian'&&<div className="sg-actions">{['♠','♥','♣','♦'].map(suit=><button disabled={disabled} key={suit} onClick={()=>send({type:'respond',suit})}>{suit}</button>)}</div>}
 <div className="sg-hand" aria-label="你的手牌">{g.hand.map((c:SGCard)=><Card key={c.id} c={c} chosen={cards.includes(c.id)} click={()=>toggleCard(c)} disabled={!can}/>)}</div><p className="sg-detail">{info||'点击技能查看说明，点击牌查看类型与效果。可多选手牌及目标；目标按点击顺序排列。'}</p><p className="sg-selection">已选 {cards.length} 张牌{targets.length?` · 目标：${names(targets)}`:''}</p>
 <div className="sg-actions">{can&&<><label>转化 <select value={skill} onChange={e=>setSkill(e.target.value)}><option value="">原牌</option>{[...(mine.hero?.skills||[]).filter((s:string)=>convert.includes(s)),...(mine.equipment.weapon?.name==='丈八蛇矛'?['丈八蛇矛']:[])].map((s:string)=><option key={s}>{s}</option>)}</select></label>{playing&&<><button className="primary" disabled={!cards.length} onClick={()=>send({type:'play',...payload})}>出牌 / 装备</button><button onClick={()=>send({type:'end'})}>结束回合</button>{mine.hero?.skills.filter((s:string)=>active.includes(s)&&(s!=='激将'||mine.role==='lord')).map((s:string)=><button key={s} disabled={!!g.used?.[s]} title={mine.hero.text} onClick={()=>send({...payload,type:'skill',skill:s})}>发动{s}</button>)}</>}{responding&&!['guanxing','zone','horse','harvest','fanjian'].includes(r.kind)&&<button className="primary" onClick={()=>send({...payload,type:r.kind==='drawSkill'?'skill':'respond',...(r.kind==='drawSkill'?{skill:r.skill}:{})})}>{['luoshen','trigger','drawSkill'].includes(r.kind)?`发动${r.skill||'洛神'}`:r.kind==='discard'?'确认弃牌':r.kind==='yiji'?'赠送选中牌':'确认响应'}</button>}{responding&&r.kind==='respond'&&<>{mine.equipment.armor?.name==='八卦阵'&&!r.baguaUsed&&r.need==='闪'&&<button onClick={()=>send({type:'skill',skill:'八卦阵'})}>八卦阵</button>}{mine.role==='lord'&&!r.assistUsed&&mine.hero.skills.filter((s:string)=>(s==='护驾'&&r.need==='闪')||(s==='激将'&&r.need==='杀')).map((s:string)=><button key={s} onClick={()=>send({type:'skill',skill:s})}>{s}</button>)}</>}{responding&&!required&&<button onClick={()=>send({type:'pass'})}>{r.kind==='drawSkill'?'正常摸牌':r.kind==='yiji'?'保留其余牌':'放弃 / 不发动'}</button>}<button onClick={()=>{setCards([]);setTargets([]);setSkill('')}}>清空选择</button></>}</div></div>
 <details className="sg-log"><summary>对局记录 · 身份胜利条件</summary><p>主公、忠臣：消灭所有反贼和内奸。反贼：主公阵亡。内奸：最后独自存活。阵亡者身份公开。</p>{g.log.map((s:string,i:number)=><div key={i}>{s}</div>)}</details>
 {g.phase==='selectHero'&&g.candidates?.length>0&&<div className="sg-overlay"><div className="sg-dialog"><h2>选择你的武将</h2><p>你的身份：{roles[mine?.role]||'未知'}（仅你可见；主公公开）。三选一，确定后不能更换。</p><div className="sg-choices">{g.candidates.map((h:any)=><button key={h.id} disabled={disabled} onClick={()=>send({type:'selectHero',hero:h.id})}><b>{h.name}</b><small>{h.faction} · {h.hp} 体力 · {h.sex}</small><p>{h.text}</p><strong>选择 {h.name}</strong></button>)}</div></div></div>}
 </section>
}

