// Original implementation of the classic identity-card-game rules. State is JSON-only.
type G=any;
type Hero={id:string;name:string;faction:string;hp:number;sex:string;skills:string[];text:string};
export const SG_HEROES:Hero[]=[
['caocao','曹操','魏',4,'男',['奸雄','护驾'],'奸雄：受伤后可收回造成伤害的牌。护驾：主公可请魏势力代出闪。'],
['simayi','司马懿','魏',3,'男',['反馈','鬼才'],'反馈：受伤后可获得伤害来源的一张牌。鬼才：可用手牌替换判定牌。'],
['xiahoudun','夏侯惇','魏',4,'男',['刚烈'],'刚烈：受伤后可判定，非红桃令来源弃两张手牌或受伤。'],
['zhangliao','张辽','魏',4,'男',['突袭'],'突袭：摸牌阶段可改为获得至多两名其他角色各一张手牌。'],
['xuchu','许褚','魏',4,'男',['裸衣'],'裸衣：摸牌少摸一张，本回合杀、决斗伤害加一。'],
['guojia','郭嘉','魏',3,'男',['天妒','遗计'],'天妒：获得自己的判定牌。遗计：每受一点伤害可摸两张并分给角色。'],
['zhenji','甄姬','魏',3,'女',['洛神','倾国'],'洛神：回合开始可连续判定，获得黑色牌，红色停止。倾国：黑色手牌可当闪。'],
['liubei','刘备','蜀',4,'男',['仁德','激将'],'仁德：将手牌交给他人，本回合累计两张时回复一点。激将：主公可请蜀势力代出杀。'],
['guanyu','关羽','蜀',4,'男',['武圣'],'武圣：红色手牌或装备可当杀。'],
['zhangfei','张飞','蜀',4,'男',['咆哮'],'咆哮：出牌阶段使用杀不限次数。'],
['zhugeliang','诸葛亮','蜀',3,'男',['观星','空城'],'观星：开始阶段观看至多五张牌并安排牌堆顶底。空城：没有手牌时不能成为杀或决斗目标。'],
['zhaoyun','赵云','蜀',4,'男',['龙胆'],'龙胆：手牌杀和闪可互相转化。'],
['machao','马超','蜀',4,'男',['马术','铁骑'],'马术：计算与他人距离减一。铁骑：杀指定目标后可判定，红色令其不能闪。'],
['huangyueying','黄月英','蜀',3,'女',['集智','奇才'],'集智：使用非延时锦囊摸一张。奇才：锦囊不受距离限制。'],
['sunquan','孙权','吴',4,'男',['制衡','救援'],'制衡：每回合一次弃任意牌并摸等量牌。救援：主公濒死时吴势力桃额外回复一点。'],
['ganning','甘宁','吴',4,'男',['奇袭'],'奇袭：黑色手牌或装备可当过河拆桥。'],
['lumeng','吕蒙','吴',4,'男',['克己'],'克己：本回合未使用或打出杀，可跳过弃牌。'],
['huanggai','黄盖','吴',4,'男',['苦肉'],'苦肉：失去一点体力，随后摸两张牌。'],
['zhouyu','周瑜','吴',3,'男',['英姿','反间'],'英姿：摸牌阶段额外摸一张。反间：每回合一次令他人猜花色，得到你随机手牌，猜错受伤。'],
['daqiao','大乔','吴',3,'女',['国色','流离'],'国色：方片牌可当乐不思蜀。流离：成为杀目标时可弃牌转移给攻击范围内另一名角色。'],
['luxun','陆逊','吴',3,'男',['谦逊','连营'],'谦逊：不能成为顺手牵羊和乐不思蜀目标。连营：失去最后手牌时摸一张。'],
['sunshangxiang','孙尚香','吴',3,'女',['结姻','枭姬'],'结姻：每回合一次弃两手牌，与一名受伤男性各回复一点。枭姬：失去装备后摸两张。'],
['huatuo','华佗','群',3,'男',['急救','青囊'],'急救：回合外红色牌可当桃。青囊：每回合一次弃一手牌令一名角色回复一点。'],
['lvbu','吕布','群',4,'男',['无双'],'无双：杀需两张闪；决斗对手每次需两张杀。'],
['diaochan','貂蝉','群',3,'女',['离间','闭月'],'离间：每回合一次弃一牌令两名男性决斗。闭月：结束阶段摸一张。']
].map(r=>({id:r[0],name:r[1],faction:r[2],hp:r[3],sex:r[4],skills:r[5],text:r[6]} as Hero));
export type SGCard={id:string;name:string;suit:string;rank:number;type:string;slot?:string;range?:number};
export const SG_EFFECTS:Record<string,string>={借刀杀人:'指定有武器角色向其范围内另一角色使用杀，否则获得其武器。',杀:'出牌阶段限一次，对范围内角色造成1点伤害，可用闪抵消。',闪:'响应杀，抵消一次攻击。',桃:'回复1点体力，或救助濒死角色。',决斗:'双方轮流打出杀，首先不能打出者受到1点伤害。',过河拆桥:'弃置另一名角色的一张手牌、装备或判定牌。',顺手牵羊:'获得距离1以内另一名角色的一张牌。',无中生有:'摸两张牌。',南蛮入侵:'其他角色依次打出杀，否则受到1点伤害。',万箭齐发:'其他角色依次打出闪，否则受到1点伤害。',桃园结义:'所有存活角色依次回复1点体力。',五谷丰登:'亮出与存活人数相等的牌，每人依次取一张。',无懈可击:'抵消当前锦囊效果，也可抵消另一张无懈可击。',乐不思蜀:'判定不为红桃则跳过出牌阶段。',闪电:'判定黑桃2至9受到3点伤害，否则传给下家。',诸葛连弩:'攻击范围1，杀的次数不受限制。',雌雄双股剑:'攻击范围2，对异性用杀可令其弃一手牌，否则你摸一张。',青釭剑:'攻击范围2，使用杀无视防具。',青龙偃月刀:'攻击范围3，杀被闪抵消可再出杀追击。',丈八蛇矛:'攻击范围3，可将两张手牌当杀。',贯石斧:'攻击范围3，杀被闪抵消可弃两张其他牌令杀命中。',方天画戟:'攻击范围4，最后一张手牌是杀时可选择至多3个目标。',麒麟弓:'攻击范围5，杀伤害后可弃目标一匹马。',八卦阵:'需要闪时可判定，红色视为打出闪。',赤兔:'进攻马：与他人距离减一。',大宛:'进攻马：与他人距离减一。',紫骍:'进攻马：与他人距离减一。',的卢:'防御马：他人与你距离加一。',绝影:'防御马：他人与你距离加一。',爪黄飞电:'防御马：他人与你距离加一。'};
const roles:Record<number,string[]>={2:['lord','rebel'],3:['lord','rebel','renegade'],4:['lord','loyal','rebel','renegade'],5:['lord','loyal','rebel','rebel','renegade'],6:['lord','loyal','loyal','rebel','rebel','renegade']};
const requireSG=(v:any,m='当前不能这样操作')=>{if(!v)throw new Error(m)};
function shuffle<T>(a:T[]):T[]{for(let i=a.length-1;i>0;i--){const b=new Uint32Array(1);let max=Math.floor(4294967296/(i+1))*(i+1);do{crypto.getRandomValues(b)}while(b[0]>=max);const j=b[0]%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
// Classic 104-card base set; four optional EX cards are excluded.
// Card facts checked against https://zh.wikipedia.org/wiki/三國殺標準版 (standard card table).
function makeDeck(){
 const pairs:Record<string,string[]>={
 '♠':['闪电 决斗','八卦阵 雌雄双股剑','过河拆桥 顺手牵羊','过河拆桥 顺手牵羊','青龙偃月刀 绝影','乐不思蜀 青釭剑','南蛮入侵 杀','杀 杀','杀 杀','杀 杀','无懈可击 顺手牵羊','丈八蛇矛 过河拆桥','大宛 南蛮入侵'],
 '♣':['诸葛连弩 决斗','八卦阵 杀','过河拆桥 杀','过河拆桥 杀','的卢 杀','乐不思蜀 杀','南蛮入侵 杀','杀 杀','杀 杀','杀 杀','杀 杀','借刀杀人 无懈可击','借刀杀人 无懈可击'],
 '♥':['桃园结义 万箭齐发','闪 闪','桃 五谷丰登','桃 五谷丰登','麒麟弓 赤兔','桃 乐不思蜀','桃 无中生有','桃 无中生有','桃 无中生有','杀 杀','杀 无中生有','桃 过河拆桥','爪黄飞电 闪'],
 '♦':['诸葛连弩 决斗','闪 闪','闪 顺手牵羊','闪 顺手牵羊','闪 贯石斧','闪 杀','闪 杀','闪 杀','闪 杀','闪 杀','闪 闪','桃 方天画戟','杀 紫骍']};
 const weapons:Record<string,number>={诸葛连弩:1,雌雄双股剑:2,青釭剑:2,青龙偃月刀:3,丈八蛇矛:3,贯石斧:3,方天画戟:4,麒麟弓:5};
 const cards:SGCard[]=[];for(const [suit,rows]of Object.entries(pairs))rows.forEach((row,i)=>{for(const name of row.split(' ')){const slot=weapons[name]?'weapon':name==='八卦阵'?'armor':['赤兔','大宛','紫骍'].includes(name)?'offHorse':['的卢','绝影','爪黄飞电'].includes(name)?'defHorse':undefined;cards.push({id:`c${cards.length}`,name,suit,rank:i+1,type:slot?'装备':['杀','闪','桃'].includes(name)?'基本':['乐不思蜀','闪电'].includes(name)?'延时锦囊':'锦囊',...(slot?{slot}:{}),...(weapons[name]?{range:weapons[name]}:{})});}});return shuffle(cards);
}
const hero=(g:G,p:string)=>SG_HEROES.find(h=>h.id===g.sg.heroes[p]);
const has=(g:G,p:string,name:string)=>hero(g,p)?.skills.includes(name);
const red=(c:SGCard)=>c.suit==='♥'||c.suit==='♦';
const live=(g:G):string[]=>g.players.filter((p:string)=>g.sg.stats[p]?.alive);
const note=(g:G,t:string)=>{g.sg.log.push(t);g.sg.log=g.sg.log.slice(-35)};
const label=(g:G,p:string)=>hero(g,p)?.name||`${g.players.indexOf(p)+1}号`;
const stat=(g:G,p:string)=>g.sg.stats[p];
function draw(g:G,p:string,n:number){for(let i=0;i<n;i++){if(!g.sg.deck.length){g.sg.deck=shuffle(g.sg.discard.splice(0));if(!g.sg.deck.length)return}g.sg.hands[p].push(g.sg.deck.shift())}}
function top(g:G):SGCard|undefined{if(!g.sg.deck.length)g.sg.deck=shuffle(g.sg.discard.splice(0));return g.sg.deck.shift()}
function heal(g:G,p:string,n=1){const s=stat(g,p);s.hp=Math.min(s.maxHp,s.hp+n)}
function distance(g:G,a:string,b:string){const ps=live(g),i=ps.indexOf(a),j=ps.indexOf(b);return Math.max(1,Math.min(Math.abs(i-j),ps.length-Math.abs(i-j))-(has(g,a,'马术')?1:0)-(stat(g,a).equipment.offHorse?1:0)+(stat(g,b).equipment.defHorse?1:0))}
function range(g:G,p:string){return stat(g,p).equipment.weapon?.range||1}
function available(g:G,p:string):SGCard[]{return [...g.sg.hands[p],...Object.values(stat(g,p).equipment).filter(Boolean)]as SGCard[]}
function lost(g:G,p:string,hand:boolean,eq:boolean){if(!stat(g,p).alive)return;if(hand&&g.sg.hands[p].length===0&&has(g,p,'连营')){draw(g,p,1);note(g,'陆逊发动连营')}if(eq&&has(g,p,'枭姬')){draw(g,p,2);note(g,'孙尚香发动枭姬')}}
function remove(g:G,p:string,id:string,discard=true):SGCard{const hand=g.sg.hands[p]as SGCard[];let c=hand.find(x=>x.id===id);let eq=false;if(c)hand.splice(hand.indexOf(c),1);else{const slot=Object.keys(stat(g,p).equipment).find(k=>stat(g,p).equipment[k]?.id===id);requireSG(slot,'你没有这张牌');c=stat(g,p).equipment[slot!];stat(g,p).equipment[slot!]=null;eq=true}if(discard)g.sg.discard.push(c);lost(g,p,!eq,eq);return c!}
function takeZone(g:G,from:string,a:any,to?:string){let c:SGCard;const h=g.sg.hands[from]as SGCard[];if(a.zone==='hand'){requireSG(h.length,'没有手牌');const ix=shuffle(Array.from({length:h.length},(_,i)=>i))[0];c=h.splice(ix,1)[0];lost(g,from,true,false)}else if(a.zone==='delayed'){const ix=stat(g,from).delayed.findIndex((x:SGCard)=>x.id===a.card);requireSG(ix>=0,'判定牌不存在');c=stat(g,from).delayed.splice(ix,1)[0]}else{const slot=a.zone;requireSG(['weapon','armor','offHorse','defHorse'].includes(slot)&&stat(g,from).equipment[slot],'装备不存在');c=stat(g,from).equipment[slot];stat(g,from).equipment[slot]=null;lost(g,from,false,true)}if(to)g.sg.hands[to].push(c);else g.sg.discard.push(c);return c}
function queue(g:G,...jobs:any[]){g.sg.queue.unshift(...jobs)}
function pending(g:G,p:string,kind:string,data:any={}){g.sg.pending={player:p,kind,...data};g.phase=kind==='discard'?'discard':'response'}
function finish(g:G){const a=live(g),lord=g.players.find((p:string)=>g.sg.roles[p]==='lord');if(!a.includes(lord)){g.winner=a.length===1&&g.sg.roles[a[0]]==='renegade'?'renegade':'rebels'}else if(!a.some(p=>['rebel','renegade'].includes(g.sg.roles[p])))g.winner='lord';if(g.winner){g.winnerIds=g.players.filter((p:string)=>g.winner==='lord'?['lord','loyal'].includes(g.sg.roles[p]):g.winner==='rebels'?g.sg.roles[p]==='rebel':p===a[0]);g.phase='finished';g.sg.queue=[];g.sg.pending=null}}
function kill(g:G,p:string,source?:string){const s=stat(g,p);s.alive=false;g.sg.discard.push(...g.sg.hands[p],...Object.values(s.equipment).filter(Boolean),...s.delayed);g.sg.hands[p]=[];s.equipment={weapon:null,armor:null,offHorse:null,defHorse:null};s.delayed=[];note(g,`${label(g,p)}阵亡，身份${g.sg.roles[p]}`);finish(g);if(g.winner)return;if(source&&stat(g,source).alive){if(g.sg.roles[p]==='rebel')draw(g,source,3);if(g.sg.roles[source]==='lord'&&g.sg.roles[p]==='loyal'){for(const c of available(g,source))remove(g,source,c.id)}}}
export function sanguoshaSetup(g:G){requireSG(roles[g.players.length],'三国杀支持2至6人');const rs=shuffle([...roles[g.players.length]]),hs=shuffle(SG_HEROES.map(h=>h.id));g.sg={roles:Object.fromEntries(g.players.map((p:string,i:number)=>[p,rs[i]])),candidates:Object.fromEntries(g.players.map((p:string,i:number)=>[p,hs.slice(i*3,i*3+3)])),heroes:{},hands:Object.fromEntries(g.players.map((p:string)=>[p,[]])),stats:Object.fromEntries(g.players.map((p:string)=>[p,{hp:0,maxHp:0,alive:true,equipment:{weapon:null,armor:null,offHorse:null,defHorse:null},delayed:[]}])),deck:makeDeck(),discard:[],queue:[],pending:null,used:{},log:[],round:0};g.turn=g.players[rs.indexOf('lord')];g.phase='selectHero'}
function begin(g:G,p:string){g.turn=p;g.sg.used={sha:0,ren:0};g.sg.round++;queue(g,{kind:'prepare',player:p},{kind:'delays',player:p},{kind:'drawPhase',player:p},{kind:'playPhase',player:p})}
function judgment(g:G,p:string,purpose:string,data:any={}){const c=top(g);if(!c)return;note(g,`${label(g,p)}判定：${c.suit}${c.rank} ${c.name}`);const judges=live(g).filter(x=>has(g,x,'鬼才'));queue(g,{kind:'judgeReplace',player:p,purpose,data,card:c,judges,index:0})}
function judgeResult(g:G,j:any){const c=j.card as SGCard,p=j.player;const granted=has(g,p,'天妒');if(granted)g.sg.hands[p].push(c);else if(j.purpose!=='luoshen'||red(c))g.sg.discard.push(c);if(j.purpose==='luoshen'){if(!red(c)){if(!granted)g.sg.hands[p].push(c);pending(g,p,'luoshen')}return}if(j.purpose==='lebu'){if(c.suit!=='♥')g.sg.used.skipPlay=true;return}if(j.purpose==='lightning'){if(c.suit==='♠'&&c.rank>=2&&c.rank<=9){g.sg.discard.push(j.data.delayed);queue(g,{kind:'damage',target:p,amount:3,source:null,cards:[j.data.delayed.id]});}else{const next=nextAlive(g,p);if(next&&next!==p&&!stat(g,next).delayed.some((x:SGCard)=>x.name==='闪电'))stat(g,next).delayed.push(j.data.delayed);else g.sg.discard.push(j.data.delayed)}return}if(j.purpose==='bagua'){if(red(c))responseSuccess(g,j.data.response);else pending(g,p,'respond',{...j.data.response,baguaUsed:true});return}if(j.purpose==='tieqi'){queue(g,{...j.data.attack,kind:red(c)?'hit':'attackResponse'});return}if(j.purpose==='ganglie'&&c.suit!=='♥'&&j.data.source&&stat(g,j.data.source).alive){pending(g,j.data.source,'ganglie',{source:p});}}
function nextAlive(g:G,p:string){for(let n=1;n<=g.players.length;n++){const id=g.players[(g.players.indexOf(p)+n)%g.players.length];if(stat(g,id).alive)return id}return null}
function requestResponse(g:G,j:any){pending(g,j.target,'respond',{job:j,need:j.need||'闪',remaining:j.remaining||1,baguaUsed:false})}
function responseSuccess(g:G,r:any){const j=r.job;if(r.remaining>1){pending(g,j.target,'respond',{...r,remaining:r.remaining-1,baguaUsed:false});return}if(j.kind==='duel'){queue(g,{...j,target:j.source,source:j.target,remaining:has(g,j.target,'无双')?2:1});return}if(j.kind==='attackResponse'){const w=stat(g,j.source).equipment.weapon?.name;if(w==='青龙偃月刀'||w==='贯石斧'){pending(g,j.source,'weaponFollow',{job:j,weapon:w});return}}note(g,`${label(g,j.target)}成功响应`)}
function applyDamage(g:G,j:any){if(!stat(g,j.target).alive)return;const p=j.target,n=j.amount||1;stat(g,p).hp-=n;note(g,`${label(g,p)}受到${n}点${j.loss?'体力流失':'伤害'}`);const after:any[]=[];if(!j.loss){if(has(g,p,'奸雄'))after.push({kind:'trigger',player:p,skill:'奸雄',damage:j});if(has(g,p,'反馈')&&j.source&&available(g,j.source).length)after.push({kind:'trigger',player:p,skill:'反馈',damage:j});if(has(g,p,'刚烈')&&j.source)after.push({kind:'trigger',player:p,skill:'刚烈',damage:j});if(has(g,p,'遗计'))for(let i=0;i<n;i++)after.push({kind:'trigger',player:p,skill:'遗计',damage:j});if(j.sha&&j.source&&stat(g,j.source).equipment.weapon?.name==='麒麟弓'&&(stat(g,p).equipment.offHorse||stat(g,p).equipment.defHorse))after.push({kind:'horse',player:j.source,target:p});}if(stat(g,p).hp<=0)queue(g,{kind:'dying',target:p,source:j.source,responders:live(g),index:0},...after);else queue(g,...after)}
function run(g:G){let guard=0;while(!g.sg.pending&&g.sg.queue.length&&!g.winner){requireSG(++guard<200,'结算过长');const j=g.sg.queue.shift(),p=j.player;if(p&&!stat(g,p)?.alive&&j.kind!=='nextTurn')continue;
 if(j.kind==='prepare'){if(has(g,p,'观星')){const cards=[];for(let i=0;i<Math.min(5,live(g).length);i++){const c=top(g);if(c)cards.push(c)}pending(g,p,'guanxing',{cards});}else if(has(g,p,'洛神'))pending(g,p,'luoshen');}
 else if(j.kind==='delays'){const ds=stat(g,p).delayed.splice(0);queue(g,...ds.reverse().map((c:SGCard)=>({kind:'nullStart',effect:{kind:'delayed',player:p,target:p,card:c}})));}
 else if(j.kind==='delayed'){if(j.card.name==='乐不思蜀'){g.sg.discard.push(j.card);judgment(g,p,'lebu')}else judgment(g,p,'lightning',{delayed:j.card});}
 else if(j.kind==='drawPhase'){if(has(g,p,'突袭'))pending(g,p,'drawSkill',{skill:'突袭'});else if(has(g,p,'裸衣'))pending(g,p,'drawSkill',{skill:'裸衣'});else draw(g,p,has(g,p,'英姿')?3:2);}
 else if(j.kind==='playPhase'){if(g.sg.used.skipPlay)queue(g,{kind:'endPhase',player:p});else g.phase='play';}
 else if(j.kind==='endPhase'){const excess=g.sg.hands[p].length-Math.max(0,stat(g,p).hp);if(excess>0&&!(has(g,p,'克己')&&!g.sg.used.shaAny)){pending(g,p,'discard',{count:excess});queue(g,{kind:'finishPhase',player:p})}else queue(g,{kind:'finishPhase',player:p});}
 else if(j.kind==='finishPhase'){if(has(g,p,'闭月'))draw(g,p,1);queue(g,{kind:'nextTurn',player:p});}
 else if(j.kind==='nextTurn'){const next=nextAlive(g,p);if(next)begin(g,next);}
 else if(j.kind==='judgeReplace'){if(j.index<j.judges.length){pending(g,j.judges[j.index],'guicai',{judgment:j});}else judgeResult(g,j);}
 else if(j.kind==='nullStart'){const ps=live(g);queue(g,{kind:'nullAsk',effect:j.effect,responders:ps,index:0,negated:false});}
 else if(j.kind==='nullAsk'){if(j.index>=j.responders.length){if(!j.negated)queue(g,j.effect);else{note(g,'锦囊效果被无懈可击抵消');if(j.effect.kind==='delayed')g.sg.discard.push(j.effect.card)} }else pending(g,j.responders[j.index],'nullify',{chain:j});}
 else if(j.kind==='attack'){if(!stat(g,j.target).alive)continue;if(has(g,j.target,'流离')&&available(g,j.target).length){pending(g,j.target,'liuli',{job:j});}else queue(g,{...j,kind:'attackWeapon'});}
 else if(j.kind==='attackWeapon'){if(stat(g,j.source).equipment.weapon?.name==='雌雄双股剑'&&hero(g,j.source)?.sex!==hero(g,j.target)?.sex)pending(g,j.target,'cixiong',{job:j});else queue(g,{...j,kind:'attackJudge'});}
 else if(j.kind==='attackJudge'){if(has(g,j.source,'铁骑')){judgment(g,j.source,'tieqi',{attack:j});}else queue(g,{...j,kind:'attackResponse'});}
 else if(j.kind==='attackResponse')requestResponse(g,{...j,need:'闪',remaining:has(g,j.source,'无双')?2:1});
 else if(j.kind==='hit')queue(g,{kind:'damage',target:j.target,source:j.source,amount:1+(g.sg.used.naked&&j.source===g.turn?1:0),cards:j.cards,sha:true});
 else if(j.kind==='duel'||j.kind==='aoe'){if(stat(g,j.target).alive)requestResponse(g,j);}
 else if(j.kind==='damage')applyDamage(g,j);
 else if(j.kind==='collateral'){if(stat(g,j.target).alive&&stat(g,j.target).equipment.weapon)pending(g,j.target,'collateral',{job:j});}
 else if(j.kind==='draw')draw(g,j.target,j.count);
 else if(j.kind==='heal'){if(stat(g,j.target).alive)heal(g,j.target);}
 else if(j.kind==='zone'){if(available(g,j.target).length||stat(g,j.target).delayed.length)pending(g,j.source,'zone',{job:j});}
 else if(j.kind==='harvest'){if(g.sg.harvest?.length)pending(g,j.target,'harvest',{cards:g.sg.harvest});}
 else if(j.kind==='harvestEnd'){g.sg.discard.push(...g.sg.harvest);g.sg.harvest=[];}
 else if(j.kind==='dying'){if(stat(g,j.target).hp>0)continue;if(j.index>=j.responders.length){kill(g,j.target,j.source);if(g.turn===j.target&&!g.winner){g.sg.queue=g.sg.queue.filter((q:any)=>q.kind!=='nextTurn');g.sg.queue.push({kind:'nextTurn',player:j.target})}}else if(stat(g,j.responders[j.index]).alive)pending(g,j.responders[j.index],'dying',{job:j});else queue(g,{...j,index:j.index+1});}
 else if(j.kind==='trigger'){pending(g,p,'trigger',{skill:j.skill,damage:j.damage});}
 else if(j.kind==='horse')pending(g,p,'horse',{target:j.target});
 }
 if(!g.sg.pending&&!g.winner&&g.phase!=='selectHero')g.phase='play';
}
function virtual(g:G,p:string,a:any,need?:string){const ids=Array.isArray(a.cards)?a.cards:[a.card];requireSG(ids.length&&new Set(ids).size===ids.length,'请选择牌');const cards=ids.map((id:string)=>available(g,p).find(c=>c.id===id));requireSG(cards.every(Boolean),'你没有这些牌');let name=cards[0].name;const skill=a.skill;if(skill==='武圣'){requireSG(has(g,p,skill)&&cards.length===1&&red(cards[0]));name='杀'}else if(skill==='倾国'){requireSG(has(g,p,skill)&&cards.length===1&&!red(cards[0])&&g.sg.hands[p].includes(cards[0]));name='闪'}else if(skill==='龙胆'){requireSG(has(g,p,skill)&&cards.length===1&&['杀','闪'].includes(name)&&g.sg.hands[p].includes(cards[0]));name=name==='杀'?'闪':'杀'}else if(skill==='奇袭'){requireSG(has(g,p,skill)&&cards.length===1&&!red(cards[0]));name='过河拆桥'}else if(skill==='国色'){requireSG(has(g,p,skill)&&cards.length===1&&cards[0].suit==='♦');name='乐不思蜀'}else if(skill==='急救'){requireSG(has(g,p,skill)&&p!==g.turn&&cards.length===1&&red(cards[0]));name='桃'}else if(skill==='丈八蛇矛'){requireSG(stat(g,p).equipment.weapon?.name===skill&&cards.length===2&&cards.every((c:SGCard)=>g.sg.hands[p].includes(c)));name='杀'}else{requireSG(!skill&&cards.length===1&&g.sg.hands[p].includes(cards[0]),'需合法的手牌或转化技能')}if(need)requireSG(name===need,`请打出${need}`);return {name,cards:cards as SGCard[],ids,skill};}
function spend(g:G,p:string,v:any){for(const c of v.cards)remove(g,p,c.id);if(v.name==='杀'&&p===g.turn)g.sg.used.shaAny=true;note(g,`${label(g,p)}${v.skill?'发动'+v.skill+'，':''}打出${v.name}`)}
function canTarget(g:G,p:string,t:string,name:string){requireSG(g.players.includes(t)&&stat(g,t).alive,'请选择存活角色');if(['杀','决斗','过河拆桥','顺手牵羊','乐不思蜀'].includes(name))requireSG(t!==p,'不能指定自己');if(['杀','决斗'].includes(name))requireSG(!(has(g,t,'空城')&&!g.sg.hands[t].length),'空城：不能指定无手牌诸葛亮');if(['顺手牵羊','乐不思蜀'].includes(name))requireSG(!has(g,t,'谦逊'),'谦逊：不能指定陆逊');if(name==='杀')requireSG(distance(g,p,t)<=range(g,p),'目标不在攻击范围');if(name==='顺手牵羊')requireSG(has(g,p,'奇才')||distance(g,p,t)<=1,'顺手牵羊距离为1');if(['过河拆桥','顺手牵羊'].includes(name))requireSG(available(g,t).length||stat(g,t).delayed.length,'目标没有牌');if(name==='乐不思蜀')requireSG(!stat(g,t).delayed.some((c:SGCard)=>c.name===name),'目标已有乐不思蜀');}
function play(g:G,p:string,a:any){const v=virtual(g,p,a),name=v.name,t=a.target;const targeted=['杀','决斗','过河拆桥','顺手牵羊','乐不思蜀'];if(targeted.includes(name))canTarget(g,p,t,name);let ts=[t];if(name==='杀'){requireSG(!g.sg.used.sha||has(g,p,'咆哮')||stat(g,p).equipment.weapon?.name==='诸葛连弩','本阶段已使用过杀');ts=a.targets||[t];requireSG(Array.isArray(ts)&&ts.length>0&&new Set(ts).size===ts.length,'目标重复');requireSG(ts.length===1||stat(g,p).equipment.weapon?.name==='方天画戟'&&g.sg.hands[p].length===1&&v.cards.length===1&&ts.length<=3,'不能指定多个目标');for(const x of ts)canTarget(g,p,x,name);}if(name==='桃')requireSG(stat(g,p).hp<stat(g,p).maxHp,'体力已满');requireSG(!['闪','无懈可击'].includes(name),'此牌只能在响应时使用');if(name==='闪电')requireSG(!stat(g,p).delayed.some((c:SGCard)=>c.name==='闪电'),'已有闪电');
 if(name==='借刀杀人'){requireSG(t!==p&&live(g).includes(t)&&stat(g,t).equipment.weapon,'请选择其他有武器角色');canTarget(g,t,a.secondaryTarget,'杀');}
 const c=v.cards[0];if(c.type==='装备'&&!v.skill){remove(g,p,c.id,false);const old=stat(g,p).equipment[c.slot!];if(old)remove(g,p,old.id);stat(g,p).equipment[c.slot!]=c;note(g,`${label(g,p)}装备${c.name}`);return}
 spend(g,p,v);const cs=v.cards.map((x:SGCard)=>x.id);if(name==='杀'){g.sg.used.sha++;queue(g,...ts.map(x=>({kind:'attack',target:x,source:p,cards:cs})));return}if(name==='桃'){heal(g,p);return}if(name==='乐不思蜀'||name==='闪电'){g.sg.discard=g.sg.discard.filter((x:SGCard)=>x.id!==c.id);stat(g,name==='闪电'?p:t).delayed.push({...c,name,type:'延时锦囊'});return}
 if(has(g,p,'集智'))draw(g,p,1);let effects:any[]=[];if(name==='借刀杀人')effects=[{kind:'collateral',source:p,target:t,victim:a.secondaryTarget}];if(name==='决斗')effects=[{kind:'duel',target:t,source:p,need:'杀',remaining:has(g,p,'无双')?2:1,cards:cs}];if(name==='无中生有')effects=[{kind:'draw',target:p,count:2}];if(name==='过河拆桥'||name==='顺手牵羊')effects=[{kind:'zone',source:p,target:t,gain:name==='顺手牵羊'}];if(name==='南蛮入侵'||name==='万箭齐发')effects=order(g,p).filter(x=>x!==p).map(x=>({kind:'aoe',source:p,target:x,need:name==='南蛮入侵'?'杀':'闪',cards:cs}));if(name==='桃园结义')effects=order(g,p).map(x=>({kind:'heal',target:x}));if(name==='五谷丰登'){g.sg.harvest=[];for(const x of live(g)){const c=top(g);if(c)g.sg.harvest.push(c)}effects=order(g,p).map(x=>({kind:'harvest',target:x}));}queue(g,...effects.map(effect=>({kind:'nullStart',effect})),...(name==='五谷丰登'?[{kind:'harvestEnd'}]:[]));
}
function order(g:G,p:string){const i=g.players.indexOf(p);return [...g.players.slice(i),...g.players.slice(0,i)].filter((x:string)=>stat(g,x).alive)as string[]}
export function sanguoshaAct(g:G,p:string,a:any){requireSG(g.players.includes(p)&&!g.winner,'本局已结束或你不在本局');if(g.phase==='selectHero'){requireSG(a.type==='selectHero'&&!g.sg.heroes[p]&&g.sg.candidates[p].includes(a.hero),'请选择自己的候选武将');g.sg.heroes[p]=a.hero;const h=hero(g,p)!;stat(g,p).hp=stat(g,p).maxHp=h.hp+(g.players.length>=5&&g.sg.roles[p]==='lord'?1:0);if(g.players.every((x:string)=>g.sg.heroes[x])){for(const x of g.players)draw(g,x,5);g.sg.candidates={};begin(g,g.turn);run(g)}return}
 requireSG(stat(g,p).alive,'你已阵亡');if(g.sg.pending){requireSG(g.sg.pending.player===p,'等待其他玩家响应');respond(g,p,a);run(g);return}requireSG(g.turn===p&&g.phase==='play','还没轮到你出牌');if(a.type==='end'){queue(g,{kind:'endPhase',player:p});}else if(a.type==='skill')activeSkill(g,p,a);else{requireSG(a.type==='play','未知操作');play(g,p,a)}run(g)}
export function sanguoshaView(g:G,p:string){const s=g.sg,pen=s.pending;return {kind:g.kind,players:g.players,turn:g.turn,phase:g.phase,winner:g.winner,winnerIds:g.winnerIds||[],round:s.round,hand:s.hands[p]||[],candidates:!s.heroes[p]?(s.candidates[p]||[]).map((id:string)=>SG_HEROES.find(h=>h.id===id)):[],seats:g.players.map((x:string)=>({id:x,hero:hero(g,x)||null,role:g.winner||x===p||s.roles[x]==='lord'||!stat(g,x).alive?s.roles[x]:null,...stat(g,x),handCount:s.hands[x].length,distance:s.heroes[p]?distance(g,p,x):1})),pendingPlayers:g.phase==='selectHero'?g.players.filter((x:string)=>!s.heroes[x]):pen?[pen.player]:g.winner?[]:[g.turn],pending:pen?publicPending(g,p,pen):null,log:s.log,deckCount:s.deck.length,discardCount:s.discard.length,lastCard:s.discard.at(-1)||null,used:s.used,harvest:s.harvest||[]};}
function publicPending(g:G,p:string,pen:any){if(pen.player!==p)return {player:pen.player,kind:pen.kind};const copy=JSON.parse(JSON.stringify(pen));if(copy.judgment)delete copy.judgment.judges;return copy}
function selected(g:G,p:string,a:any,n?:number,handOnly=false):SGCard[]{const ids=a.cards||[a.card];requireSG(Array.isArray(ids)&&ids.length>0&&new Set(ids).size===ids.length&&(n===undefined||ids.length===n),'请选择正确数量的牌');const cs=ids.map((id:string)=>(handOnly?g.sg.hands[p]:available(g,p)).find((c:SGCard)=>c.id===id));requireSG(cs.every(Boolean),'请选择自己的牌');return cs}
function activeSkill(g:G,p:string,a:any){const skill=a.skill;requireSG(has(g,p,skill),'没有这个武将技能');const t=a.target;const once=['制衡','青囊','结姻','反间','离间'];if(once.includes(skill))requireSG(!g.sg.used[skill],'本回合已发动此技能');
 if(skill==='仁德'){requireSG(t!==p&&live(g).includes(t),'请选择其他存活角色');const cs=selected(g,p,a,undefined,true);for(const c of cs){remove(g,p,c.id,false);g.sg.hands[t].push(c)}const old=g.sg.used.ren;g.sg.used.ren+=cs.length;if(old<2&&g.sg.used.ren>=2)heal(g,p);}
 else if(skill==='制衡'){const cs=selected(g,p,a);for(const c of cs)remove(g,p,c.id);draw(g,p,cs.length);g.sg.used[skill]=true;}
 else if(skill==='青囊'){requireSG(live(g).includes(t)&&stat(g,t).hp<stat(g,t).maxHp,'请选择受伤角色');const cs=selected(g,p,a,1,true);remove(g,p,cs[0].id);heal(g,t);g.sg.used[skill]=true;}
 else if(skill==='结姻'){requireSG(t!==p&&live(g).includes(t)&&hero(g,t)?.sex==='男'&&stat(g,t).hp<stat(g,t).maxHp,'请选择其他受伤男性');const cs=selected(g,p,a,2,true);for(const c of cs)remove(g,p,c.id);heal(g,p);heal(g,t);g.sg.used[skill]=true;}
 else if(skill==='苦肉'){queue(g,{kind:'damage',target:p,amount:1,loss:true,source:null},{kind:'draw',player:p,target:p,count:2});}
 else if(skill==='反间'){requireSG(t!==p&&live(g).includes(t)&&g.sg.hands[p].length,'请选择其他角色且至少有一张手牌');g.sg.used[skill]=true;pending(g,t,'fanjian',{source:p});}
 else if(skill==='离间'){const ts=a.targets;requireSG(Array.isArray(ts)&&ts.length===2&&ts[0]!==ts[1]&&ts.every((x:string)=>x!==p&&live(g).includes(x)&&hero(g,x)?.sex==='男'),'请选择两名其他男性');canTarget(g,ts[1],ts[0],'决斗');const cs=selected(g,p,a,1);remove(g,p,cs[0].id);g.sg.used[skill]=true;queue(g,{kind:'duel',source:ts[1],target:ts[0],need:'杀',remaining:has(g,ts[1],'无双')?2:1,cards:[]});}
 else if(skill==='激将'){requireSG(g.sg.roles[p]==='lord','激将仅主公可发动');requireSG(!g.sg.used.sha||has(g,p,'咆哮')||stat(g,p).equipment.weapon?.name==='诸葛连弩','本阶段已使用过杀');canTarget(g,p,t,'杀');startAssist(g,p,'杀',{kind:'assistAttack',target:t});}
 else requireSG(false,'此技能需通过用牌转化或在响应时发动');note(g,`${label(g,p)}发动${skill}`);
}
function startAssist(g:G,p:string,need:string,original:any){const faction=need==='杀'?'蜀':'魏';const allies=order(g,p).filter(x=>x!==p&&hero(g,x)?.faction===faction);requireSG(allies.length,'没有可响应的同势力角色');pending(g,allies[0],'assist',{requester:p,need,allies,index:0,original});}
function resumeAssist(g:G,r:any,success:boolean,cards:string[]=[]){if(success){if(r.original.kind==='assistAttack'){g.sg.used.sha++;g.sg.used.shaAny=true;queue(g,{kind:'attack',source:r.requester,target:r.original.target,cards})}else responseSuccess(g,r.original);return}const ix=r.index+1;if(ix<r.allies.length){pending(g,r.allies[ix],'assist',{...r,index:ix,player:r.allies[ix]});return}if(r.original.kind!=='assistAttack')pending(g,r.requester,'respond',{...r.original,assistUsed:true,player:r.requester});else note(g,'没有角色响应激将');}
function failResponse(g:G,r:any){const j=r.job;queue(g,{kind:'damage',target:j.target,source:j.source,amount:1+((j.kind==='duel'||j.kind==='attackResponse')&&g.sg.used.naked&&j.source===g.turn?1:0),cards:j.cards||[],sha:j.kind==='attackResponse'});}
function respond(g:G,p:string,a:any){const r=g.sg.pending;const pass=a.type==='pass';
 if(r.kind==='respond'){
  if(pass){g.sg.pending=null;failResponse(g,r);return}
  if(a.type==='skill'&&a.skill==='八卦阵'){requireSG(r.need==='闪'&&!r.baguaUsed&&stat(g,p).equipment.armor?.name==='八卦阵'&&!(r.job.kind==='attackResponse'&&stat(g,r.job.source).equipment.weapon?.name==='青釭剑'),'不能发动八卦阵');g.sg.pending=null;judgment(g,p,'bagua',{response:r});return}
  if(a.type==='skill'&&['护驾','激将'].includes(a.skill)){requireSG(!r.assistUsed&&g.sg.roles[p]==='lord'&&has(g,p,a.skill)&&r.need===(a.skill==='护驾'?'闪':'杀'),'不能发动主公技');startAssist(g,p,r.need,r);return}
  requireSG(a.type==='respond'||a.type==='play','请出牌响应或放弃');const v=virtual(g,p,a,r.need);spend(g,p,v);g.sg.pending=null;responseSuccess(g,r);return;
 }
 if(r.kind==='collateral'){if(pass){takeZone(g,p,{zone:'weapon'},r.job.source);g.sg.pending=null;return}const v=virtual(g,p,a,'杀');canTarget(g,p,r.job.victim,'杀');spend(g,p,v);g.sg.pending=null;queue(g,{kind:'attack',source:p,target:r.job.victim,cards:v.cards.map(c=>c.id)});return;}
 if(r.kind==='nullify'){const chain=r.chain;if(pass){g.sg.pending=null;queue(g,{...chain,index:chain.index+1});return}const v=virtual(g,p,a,'无懈可击');spend(g,p,v);g.sg.pending=null;queue(g,{...chain,index:0,responders:order(g,nextAlive(g,p)!),negated:!chain.negated});return;}
 if(r.kind==='dying'){if(pass){g.sg.pending=null;queue(g,{...r.job,index:r.job.index+1});return}const v=virtual(g,p,a,'桃');spend(g,p,v);const t=r.job.target;heal(g,t,has(g,t,'救援')&&g.sg.roles[t]==='lord'&&p!==t&&hero(g,p)?.faction==='吴'?2:1);g.sg.pending=null;if(stat(g,t).hp<=0)queue(g,r.job);else note(g,`${label(g,t)}脱离濒死`);return;}
 if(r.kind==='assist'){if(pass){g.sg.pending=null;resumeAssist(g,r,false);return}const v=virtual(g,p,a,r.need);spend(g,p,v);g.sg.pending=null;resumeAssist(g,r,true,v.cards.map(c=>c.id));return;}
 if(r.kind==='discard'){const cs=selected(g,p,a,r.count,true);for(const c of cs)remove(g,p,c.id);g.sg.pending=null;return;}
 if(r.kind==='drawSkill'){if(pass){draw(g,p,2);g.sg.pending=null;return}requireSG(a.type==='skill','请选择摸牌技能或正常摸牌');if(r.skill==='裸衣'){draw(g,p,1);g.sg.used.naked=true;}else{const ts=a.targets;requireSG(Array.isArray(ts)&&ts.length>=1&&ts.length<=2&&new Set(ts).size===ts.length&&ts.every((x:string)=>x!==p&&live(g).includes(x)&&g.sg.hands[x].length),'选择一至两名有手牌角色');for(const t of ts)takeZone(g,t,{zone:'hand'},p)}g.sg.pending=null;note(g,`${label(g,p)}发动${r.skill}`);return;}
 if(r.kind==='guanxing'){const topIds=a.top||[],bottomIds=a.bottom||[];const ids=[...topIds,...bottomIds];requireSG(Array.isArray(topIds)&&Array.isArray(bottomIds)&&ids.length===r.cards.length&&new Set(ids).size===ids.length&&ids.every((id:string)=>r.cards.some((c:SGCard)=>c.id===id)),'请将所有牌安排到牌堆顶或底');g.sg.deck.unshift(...topIds.map((id:string)=>r.cards.find((c:SGCard)=>c.id===id)));g.sg.deck.push(...bottomIds.map((id:string)=>r.cards.find((c:SGCard)=>c.id===id)));g.sg.pending=null;return;}
 if(r.kind==='luoshen'){g.sg.pending=null;if(!pass)judgment(g,p,'luoshen');return;}
 if(r.kind==='guicai'){const j=r.judgment;if(!pass){const cs=selected(g,p,a,1,true);remove(g,p,cs[0].id,false);g.sg.discard.push(j.card);j.card=cs[0];note(g,`司马懿改判为${cs[0].suit}${cs[0].rank} ${cs[0].name}`)}g.sg.pending=null;queue(g,{...j,index:j.index+1});return;}
 if(r.kind==='ganglie'){if(!pass){const cs=selected(g,p,a,2,true);for(const c of cs)remove(g,p,c.id)}else queue(g,{kind:'damage',source:r.source,target:p,amount:1,cards:[]});g.sg.pending=null;return;}
 if(r.kind==='trigger'){if(pass){g.sg.pending=null;return}g.sg.pending=null;if(r.skill==='奸雄'){const ids=r.damage.cards||[];const cs=g.sg.discard.filter((c:SGCard)=>ids.includes(c.id));g.sg.discard=g.sg.discard.filter((c:SGCard)=>!ids.includes(c.id));g.sg.hands[p].push(...cs)}else if(r.skill==='反馈'){pending(g,p,'zone',{job:{source:p,target:r.damage.source,gain:true,noDelayed:true}})}else if(r.skill==='刚烈')judgment(g,p,'ganglie',{source:r.damage.source});else if(r.skill==='遗计'){const before=new Set(g.sg.hands[p].map((c:SGCard)=>c.id));draw(g,p,2);pending(g,p,'yiji',{cards:g.sg.hands[p].filter((c:SGCard)=>!before.has(c.id))});}return;}
 if(r.kind==='yiji'){if(pass){g.sg.pending=null;return}const t=a.target;requireSG(live(g).includes(t)&&t!==p,'请选择其他存活角色');const cs=selected(g,p,a,undefined,true);requireSG(cs.every(c=>r.cards.some((x:SGCard)=>x.id===c.id)),'仅可分配遗计摸到的牌');for(const c of cs){remove(g,p,c.id,false);g.sg.hands[t].push(c)}r.cards=r.cards.filter((c:SGCard)=>!cs.some(x=>x.id===c.id));if(!r.cards.length)g.sg.pending=null;return;}
 if(r.kind==='zone'){requireSG(!(r.job.noDelayed&&a.zone==='delayed'),'反馈不能取判定牌');takeZone(g,r.job.target,a,r.job.gain?p:undefined);g.sg.pending=null;return;}
 if(r.kind==='harvest'){const ix=g.sg.harvest.findIndex((c:SGCard)=>c.id===a.card);requireSG(ix>=0,'请选择五谷牌');g.sg.hands[p].push(g.sg.harvest.splice(ix,1)[0]);g.sg.pending=null;return;}
 if(r.kind==='fanjian'){requireSG(['♠','♥','♣','♦'].includes(a.suit),'请选择花色');const c=takeZone(g,r.source,{zone:'hand'},p);note(g,`${label(g,p)}猜${a.suit}，得到${c.suit}${c.rank} ${c.name}`);g.sg.pending=null;if(a.suit!==c.suit)queue(g,{kind:'damage',target:p,source:r.source,amount:1,cards:[]});return;}
 if(r.kind==='liuli'){if(pass){g.sg.pending=null;queue(g,{...r.job,kind:'attackWeapon'});return}const t=a.target,cs=selected(g,p,a,1);requireSG(t!==p&&t!==r.job.source&&live(g).includes(t),'流离不能转给杀的来源或自己');const cost=cs[0],reach=cost.id===stat(g,p).equipment.weapon?.id?1:range(g,p),d=distance(g,p,t)+(cost.id===stat(g,p).equipment.offHorse?.id?1:0);requireSG(d<=reach&&!(has(g,t,'空城')&&!g.sg.hands[t].length),'目标不在弃牌后的攻击范围');remove(g,p,cost.id);g.sg.pending=null;queue(g,{...r.job,kind:'attackWeapon',target:t});note(g,'大乔发动流离');return;}
 if(r.kind==='cixiong'){if(pass)draw(g,r.job.source,1);else{const cs=selected(g,p,a,1,true);remove(g,p,cs[0].id)}g.sg.pending=null;queue(g,{...r.job,kind:'attackJudge'});return;}
 if(r.kind==='weaponFollow'){if(pass){g.sg.pending=null;return}if(r.weapon==='青龙偃月刀'){const v=virtual(g,p,a,'杀');canTarget(g,p,r.job.target,'杀');spend(g,p,v);g.sg.pending=null;queue(g,{...r.job,kind:'attack',cards:v.cards.map(c=>c.id)});}else{const cs=selected(g,p,a,2);requireSG(cs.every(c=>c.id!==stat(g,p).equipment.weapon?.id),'不能弃置贯石斧本身');for(const c of cs)remove(g,p,c.id);g.sg.pending=null;queue(g,{...r.job,kind:'hit'});}return;}
 if(r.kind==='horse'){if(!pass){requireSG(['offHorse','defHorse'].includes(a.zone),'请选择目标的一匹马');takeZone(g,r.target,a)}g.sg.pending=null;return;}
 requireSG(false,'未知响应');
}
